# Generated by Django 3.1.5 on 2021-03-26 05:46

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('LINE_enable', models.BooleanField(default=False)),
                ('LINE_token', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='LINE_enable',
            new_name='is_station',
        ),
        migrations.RemoveField(
            model_name='device',
            name='LINE_token',
        ),
        migrations.AlterField(
            model_name='device',
            name='key',
            field=models.CharField(blank=True, default=myapp.models.Device_KeyGenerate, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.notification'),
        ),
    ]
