# Generated by Django 3.1.5 on 2021-03-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_device_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
